lib/relax_web/router.ex
defmodule RelaxWeb.Router do
  use RelaxWeb, :router

  alias Relax.Accounts

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_flash
    plug :protect_from_forgery
    plug :put_secure_browser_headers
    plug :authenticate
    plug :put_user_token
  end

  pipeline :api do
    plug :accepts, ["json"]
  end

  scope "/", RelaxWeb do
    pipe_through [:browser]

    get "/", PageController, :index

    resources "/users", UserController, only: [:new, :create]

    resources "/session", SessionController, only: [:new, :create, :delete], singleton: true

    resources "/room", RoomController, only: [:index, :new, :show, :create, :delete]
  end

  defp authenticate(conn, _) do
    if user_id = get_session(conn, :user_id) do
      assign(conn, :current_user, Accounts.get_user!(user_id))
    else
      conn
    end
  end

  defp put_user_token(conn, _) do
    if current_user = conn.assigns[:current_user] do
      token = Phoenix.Token.sign(conn, "user socket", current_user.id)
      assign(conn, :user_token, token)
    else
      conn
    end
  end

  # Other scopes may use custom stacks.
  # scope "/api", RelaxWeb do
  #   pipe_through :api
  # end
end

lib/relax_web/views/layout_view.ex
defmodule RelaxWeb.LayoutView do
  use RelaxWeb, :view
end

lib/relax_web/templates/layout/app.html.eex
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8"/>
    <meta http-equiv="X-UA-Compatible" content="IE=edge"/>
    <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
    <title><%= assigns[:page_title] || "Relax · Phoenix Framework" %></title>
    <link rel="stylesheet" href="<%= Routes.static_path(@conn, "/css/app.css") %>"/>
    <%= csrf_meta_tag() %>
  </head>
  <body>
    <header>
        <h1>Relax</h1>
        <%= if assigns[:current_user] do %>
	  <%= form_for @conn, Routes.session_path(@conn, :delete), [method: :delete], fn _f -> %>
	    <%= submit "Logout" %>
	  <% end %>
  	<% end %>
    </header>
    <main role="main" class="container">
      <p class="alert alert-info" role="alert"><%= get_flash(@conn, :info) %></p>
      <p class="alert alert-danger" role="alert"><%= get_flash(@conn, :error) %></p>
      <%= render @view_module, @view_template, assigns %>
    </main>
    <script type="text/javascript" src="<%= Routes.static_path(@conn, "/js/app.js") %>"></script>
  </body>
</html>